---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: node-image
  type: docker-image
  source:
    repository: node
- name: ci
  type: git
  source:
    uri: https://github.com/ystros/gameteki-ci.git
    branch: master
- name: throneteki-server
  type: git
  source:
    uri: https://github.com/throneteki/throneteki.git
    branch: master
- name: throneteki-client
  type: git
  source:
    uri: https://github.com/throneteki/throneteki-client.git
    branch: master
- name: throneteki-json-data
  type: git
  source:
    uri: https://github.com/throneteki/throneteki-json-data.git
    branch: master
- name: throneteki-server-prs
  type: pull-request
  check_every: 1m
  source:
    repository: throneteki/throneteki
    access_token: ((throneteki-github-access-token))
- name: throneteki-client-prs
  type: pull-request
  check_every: 1m
  source:
    repository: throneteki/throneteki-client
    access_token: ((throneteki-github-access-token))
- name: throneteki-json-data-prs
  type: pull-request
  check_every: 1m
  source:
    repository: throneteki/throneteki-json-data
    access_token: ((throneteki-github-access-token))

groups:
- name: throneteki
  jobs:
  - run-server-tests
  - run-client-tests
  - run-json-data-tests
  - pre-build-fan-in
  - build-client
- name: throneteki-prs
  jobs:
  - run-server-pr-tests
  - run-client-pr-tests
  - run-json-data-pr-tests

jobs:
- name: run-server-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: node-image
    - get: ci
    - get: node-source
      resource: throneteki-server
      trigger: true
  - task: run-server-tests
    image: node-image
    file: ci/tasks/shared/run-npm-test.yml
- name: run-client-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: node-image
    - get: ci
    - get: node-source
      resource: throneteki-client
      trigger: true
  - task: run-client-tests
    image: node-image
    file: ci/tasks/shared/run-npm-test.yml
- name: run-json-data-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: node-image
    - get: ci
    - get: node-source
      resource: throneteki-json-data
      trigger: true
  - task: run-json-data-tests
    image: node-image
    file: ci/tasks/shared/run-npm-test.yml
- name: pre-build-fan-in
  plan:
  - get: throneteki-server
    trigger: true
    passed: [run-server-tests]
  - get: throneteki-client
    trigger: true
    passed: [run-client-tests]
  - get: throneteki-json-data
    trigger: true
    passed: [run-json-data-tests]
- name: build-client
  serial: true
  public: true
  plan:
  - aggregate:
    - get: node-image
    - get: ci
    - get: throneteki-client
      passed: [pre-build-fan-in]
      trigger: true
  - task: build-client
    image: node-image
    file: ci/tasks/throneteki/build-client.yml
- name: run-server-pr-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: node-image
    - get: ci
    - get: throneteki-server-prs
      version: every
      trigger: true
  - task: fetch-data-submodule
    file: ci/tasks/throneteki/fetch-data-submodule.yml
  - put: throneteki-server-prs
    params:
      path: throneteki-server-prs
      status: pending
  - task: run-npm-tests
    image: node-image
    file: ci/tasks/shared/run-npm-test.yml
    on_failure:
      put: throneteki-server-prs
      params:
        path: node-source
        status: failure
  - put: throneteki-server-prs
    params:
      path: throneteki-server-prs
      status: success
- name: run-client-pr-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: node-image
    - get: ci
    - get: node-source
      resource: throneteki-client-prs
      version: every
      trigger: true
  - put: throneteki-client-prs
    params:
      path: node-source
      status: pending
  - task: run-npm-tests
    image: node-image
    file: ci/tasks/shared/run-npm-test.yml
    on_failure:
      put: throneteki-client-prs
      params:
        path: node-source
        status: failure
  - put: throneteki-client-prs
    params:
      path: node-source
      status: success
- name: run-json-data-pr-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: node-image
    - get: ci
    - get: node-source
      resource: throneteki-json-data-prs
      version: every
      trigger: true
  - put: throneteki-json-data-prs
    params:
      path: node-source
      status: pending
  - task: run-json-data-tests
    image: node-image
    file: ci/tasks/shared/run-npm-test.yml
    on_failure:
      put: throneteki-json-data-prs
      params:
        path: node-source
        status: failure
  - put: throneteki-json-data-prs
    params:
      path: node-source
      status: success
