---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine/git

inputs:
  - name: ci
  - name: throneteki-server

outputs:
  - name: node-source

run:
  path: ci/tasks/throneteki/build-client
